# .golangci.yml
version: 2

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - errcheck
    - unused

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0