name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write    # 允许推送镜像到 GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install Make (if needed)
        run: sudo apt-get update && sudo apt-get install -y make

      # 🔧 新增：启用 Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ✅ 登录 GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ✅ 编译二进制
      - name: Build Binary
        run: make build

      # ✅ 构建并推送多架构镜像
      - name: Build and Push Multi-Arch Image
        env:
          IMAGE_REPO: ghcr.io/${{ github.repository }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          make docker-multiarch