name: Lint & Format

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Clean old golangci-lint
        run: |
          rm -f ./bin/golangci-lint
          mkdir -p ./bin

      - name: Install golangci-lint (latest stable)
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./bin latest
      - name: Verify golangci-lint version
        run: |
          ./bin/golangci-lint --version

      - name: Run golangci-lint
        run: ./bin/golangci-lint run --timeout=5m